name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Se a sua branch principal se chamar 'master', mude aqui para master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy para o Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GODIGITAL }}'
          channelId: live
          projectId: godigital-gestao
